version: '3.7'

# this part is mainly to bind all services to the port which are used by nginx at the target server
services:
  login-service:
    ports:
      - "8083:${LOGIN_PORT}"
  token-decrypter:
    ports:
      - "8084:${TOKEN_DECRYPTER_PORT}"
  frontend:
    ports:
      - "8085:3000"
    build:
      context: ./frontend
      args:
        # at the target server token-decrypter is available at this relative path
        REACT_APP_TOKEN_DECRYPTOR_URL: /token-decrypter
        REACT_APP_API_URL: /api
